INSERT INTO stores
VALUES
    (DEFAULT, 'Le Bistrot Belfortain', 47.638206, 6.859443),
    (DEFAULT, 'Chez Luigi - Pizzeria', 47.637923, 6.859709),
    (DEFAULT, 'La Brasserie du Coin', 47.638017, 6.857906),
    (DEFAULT, 'Café de la Rive Gauche', 47.637324, 6.857318),
    (DEFAULT, 'Sushi Savor', 47.637121, 6.857720);


INSERT INTO users
VALUES (DEFAULT, 'Jean', 'Dupont', 'Homme', 'ABC Corp', 'Ingénieur logiciel passionné par le codage.', 1),
       (DEFAULT, 'Marie', 'Martin', 'Femme', 'XYZ Ltd', 'Marketeuse expérimentée spécialisée dans les campagnes digitales.', 2),
       (DEFAULT, 'Claude', 'Lefevre', 'Homme', '123 Industries', 'Entrepreneur et propriétaire d entreprise.', 3),
       (DEFAULT, 'Isabelle', 'Roux', 'Femme', 'Tech Solutions',
        'Spécialiste en informatique avec une expertise en sécurité réseau.', 4),
       (DEFAULT, 'Pierre', 'Leroy', 'Homme', 'Data Analytics Inc.', 'Data scientist axé sur l apprentissage automatique.', 5),
       (DEFAULT, 'Camille', 'Lecomte', 'Femme', 'Finance Experts',
        'Analyste financier avec une expérience en gestion des risques.', 1),
       (DEFAULT, 'Alexandre', 'Dubois', 'Homme', 'Creative Designs',
        'Designer graphique passionné par la narration visuelle.', 2),
       (DEFAULT, 'Émilie', 'Bertrand', 'Femme', 'Green Energy Co.',
        'Ingénieur environnemental travaillant sur des solutions durables.', 3),
       (DEFAULT, 'Julie', 'Girard', 'Femme', 'Global Services',
        'Consultante en affaires internationales avec une expertise interculturelle.', 4),
       (DEFAULT, 'François', 'Lefort', 'Homme', 'Innovate Tech',
        'Chef de produit innovant stimulant les avancées technologiques.', 5),
       (DEFAULT, 'Amandine', 'Leroux', 'Femme', 'Healthcare Innovations',
        'Chercheuse médicale dédiée à la découverte de percées.', 1),
       (DEFAULT, 'Sébastien', 'Fournier', 'Homme', 'Smart Solutions',
        'Consultant en informatique spécialisé dans l intégration de systèmes.', 2),
       (DEFAULT, 'Léa', 'Moreau', 'Femme', 'Eco-friendly Living',
        'Militante de l environnement promouvant des modes de vie durables.', 3),
       (DEFAULT, 'Antoine', 'Huet', 'Homme', 'Digital Marketing Pro',
        'Stratège en marketing en ligne axé sur le retour sur investissement.', 4),
       (DEFAULT, 'Elodie', 'Dubreuil', 'Femme', 'Infinite Innovations',
        'Entrepreneure innovante explorant de nouvelles opportunités commerciales.', 5),
       (DEFAULT, 'Vincent', 'Blanchard', 'Homme', 'Global Travel Agency',
        'Passionné de voyages et expert en tourisme international.', 1),
       (DEFAULT, 'Nathalie', 'Leclerc', 'Femme', 'Future Tech Labs',
        'Visionnaire technologique repoussant les limites de l innovation.', 2),
       (DEFAULT, 'Guillaume', 'Caron', 'Homme', 'Smart Homes Inc.',
        'Spécialiste de l automatisation domiciliaire créant des espaces de vie connectés.', 3),
       (DEFAULT, 'Marine', 'Gauthier', 'Femme', 'Fashion Trends',
        'Créatrice de mode restant à la pointe des dernières tendances.', 4),
       (DEFAULT, 'Théo', 'Renard', 'Homme', 'Media Productions',
        'Producteur multimédia passionné par la narration à travers le film et la vidéo.', 5);